SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1080
SCREEN_LEFT_EDGE = -SCREEN_WIDTH / 2
SCREEN_RIGHT_EDGE = SCREEN_WIDTH / 2
SCREEN_TOP_EDGE = SCREEN_HEIGHT / 2
SCREEN_BOTTOM_EDGE = -SCREEN_HEIGHT / 2

PADDLE_START_POSITION = (0, SCREEN_BOTTOM_EDGE + 20)
BALL_START_POSITION = (0, SCREEN_BOTTOM_EDGE + 40)

VERTICAL_SURFACE = 'vertical'
HORIZONTAL_SURFACE = 'horizontal'
EAST = 0
NORTH = 90
WEST = 180
SOUTH = 270
COMPLETE_ANGLE = 360

