SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1080

SCREEN_LEFT_EDGE = -SCREEN_WIDTH / 2
SCREEN_RIGHT_EDGE = SCREEN_WIDTH / 2
SCREEN_TOP_EDGE = SCREEN_HEIGHT / 2
SCREEN_BOTTOM_EDGE = -SCREEN_HEIGHT / 2

BALL_SIZE = 20
BALL_RADIUS = BALL_SIZE / 2
PADDLE_WIDTH = 20
PADDLE_LENGTH = 5

MIN_PADDLE_ANGLE = 15
MAX_PADDLE_ANGLE = 165

PADDLE_START_POSITION = (0, SCREEN_BOTTOM_EDGE + PADDLE_WIDTH)
BALL_START_POSITION = (0, SCREEN_BOTTOM_EDGE + PADDLE_WIDTH + BALL_SIZE)

VERTICAL_SURFACE = 'vertical'
HORIZONTAL_SURFACE = 'horizontal'
EAST = 0
NORTH = 90
WEST = 180
SOUTH = 270
COMPLETE_ANGLE = 360
